// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"encoding/json"
	"time"
)

type IdentityRole struct {
	ID               string
	Name             string
	NormalizedName   string
	ConcurrencyStamp string
}

type IdentityRoleClaim struct {
	ID         int64
	RoleID     string
	ClaimType  string
	ClaimValue string
}

type IdentityUser struct {
	ID                   string
	UserName             string
	NormalizedUserName   string
	Email                string
	NormalizedEmail      string
	EmailConfirmed       bool
	PasswordHash         string
	SecurityStamp        string
	ConcurrencyStamp     string
	PhoneNumber          string
	PhoneNumberConfirmed bool
	TwoFactorEnabled     bool
	LockoutEnd           *time.Time
	LockoutEnabled       bool
	AccessFailedCount    int32
	Attributes           json.RawMessage
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type IdentityUserClaim struct {
	ID         int64
	UserID     string
	ClaimType  string
	ClaimValue string
}

type IdentityUserLogin struct {
	LoginProvider       string
	ProviderKey         string
	ProviderDisplayName string
	UserID              string
}

type IdentityUserRole struct {
	UserID string
	RoleID string
}

type IdentityUserToken struct {
	UserID        string
	LoginProvider string
	Name          string
	Value         string
}
