// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlcgen

import (
	"context"
	"encoding/json"
	"time"
)

const addRoleClaim = `-- name: AddRoleClaim :exec
INSERT INTO identity_role_claims (role_id, claim_type, claim_value) VALUES ($1,$2,$3)
`

type AddRoleClaimParams struct {
	RoleID     string
	ClaimType  string
	ClaimValue string
}

func (q *Queries) AddRoleClaim(ctx context.Context, arg AddRoleClaimParams) error {
	_, err := q.db.Exec(ctx, addRoleClaim, arg.RoleID, arg.ClaimType, arg.ClaimValue)
	return err
}

const addUserClaim = `-- name: AddUserClaim :exec
INSERT INTO identity_user_claims (user_id, claim_type, claim_value) VALUES ($1,$2,$3)
`

type AddUserClaimParams struct {
	UserID     string
	ClaimType  string
	ClaimValue string
}

func (q *Queries) AddUserClaim(ctx context.Context, arg AddUserClaimParams) error {
	_, err := q.db.Exec(ctx, addUserClaim, arg.UserID, arg.ClaimType, arg.ClaimValue)
	return err
}

const addUserLogin = `-- name: AddUserLogin :exec
INSERT INTO identity_user_logins (login_provider, provider_key, provider_display_name, user_id)
VALUES ($1,$2,$3,$4)
`

type AddUserLoginParams struct {
	LoginProvider       string
	ProviderKey         string
	ProviderDisplayName string
	UserID              string
}

func (q *Queries) AddUserLogin(ctx context.Context, arg AddUserLoginParams) error {
	_, err := q.db.Exec(ctx, addUserLogin,
		arg.LoginProvider,
		arg.ProviderKey,
		arg.ProviderDisplayName,
		arg.UserID,
	)
	return err
}

const addUserToRole = `-- name: AddUserToRole :exec
INSERT INTO identity_user_roles (user_id, role_id) VALUES ($1, $2)
ON CONFLICT (user_id, role_id) DO NOTHING
`

type AddUserToRoleParams struct {
	UserID string
	RoleID string
}

func (q *Queries) AddUserToRole(ctx context.Context, arg AddUserToRoleParams) error {
	_, err := q.db.Exec(ctx, addUserToRole, arg.UserID, arg.RoleID)
	return err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM identity_users
WHERE $1::text = '' OR normalized_user_name LIKE '%' || $1 || '%'
   OR normalized_email LIKE '%' || $1 || '%'
`

func (q *Queries) CountUsers(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIKey = `-- name: CreateAPIKey :exec
INSERT INTO identity_api_keys (id, user_id, name, prefix, key_hash, scopes, expires_at, created_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
`

type CreateAPIKeyParams struct {
	ID        string
	UserID    string
	Name      string
	Prefix    string
	KeyHash   string
	Scopes    json.RawMessage
	ExpiresAt *time.Time
	CreatedAt time.Time
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) error {
	_, err := q.db.Exec(ctx, createAPIKey,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Prefix,
		arg.KeyHash,
		arg.Scopes,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const createRole = `-- name: CreateRole :exec
INSERT INTO identity_roles (id, name, normalized_name, concurrency_stamp)
VALUES ($1,$2,$3,$4)
`

type CreateRoleParams struct {
	ID               string
	Name             string
	NormalizedName   string
	ConcurrencyStamp string
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) error {
	_, err := q.db.Exec(ctx, createRole,
		arg.ID,
		arg.Name,
		arg.NormalizedName,
		arg.ConcurrencyStamp,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO identity_users (
    id, user_name, normalized_user_name, email, normalized_email, email_confirmed,
    password_hash, security_stamp, concurrency_stamp, phone_number,
    phone_number_confirmed, two_factor_enabled, lockout_end, lockout_enabled,
    access_failed_count, attributes, is_anonymous
) VALUES (
    $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17
)
`

type CreateUserParams struct {
	ID                   string
	UserName             string
	NormalizedUserName   string
	Email                string
	NormalizedEmail      string
	EmailConfirmed       bool
	PasswordHash         string
	SecurityStamp        string
	ConcurrencyStamp     string
	PhoneNumber          string
	PhoneNumberConfirmed bool
	TwoFactorEnabled     bool
	LockoutEnd           *time.Time
	LockoutEnabled       bool
	AccessFailedCount    int32
	Attributes           json.RawMessage
	IsAnonymous          bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.UserName,
		arg.NormalizedUserName,
		arg.Email,
		arg.NormalizedEmail,
		arg.EmailConfirmed,
		arg.PasswordHash,
		arg.SecurityStamp,
		arg.ConcurrencyStamp,
		arg.PhoneNumber,
		arg.PhoneNumberConfirmed,
		arg.TwoFactorEnabled,
		arg.LockoutEnd,
		arg.LockoutEnabled,
		arg.AccessFailedCount,
		arg.Attributes,
		arg.IsAnonymous,
	)
	return err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM identity_roles WHERE id=$1
`

func (q *Queries) DeleteRole(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteRole, id)
	return err
}

const deleteRoleClaim = `-- name: DeleteRoleClaim :exec
DELETE FROM identity_role_claims WHERE role_id=$1 AND claim_type=$2 AND claim_value=$3
`

type DeleteRoleClaimParams struct {
	RoleID     string
	ClaimType  string
	ClaimValue string
}

func (q *Queries) DeleteRoleClaim(ctx context.Context, arg DeleteRoleClaimParams) error {
	_, err := q.db.Exec(ctx, deleteRoleClaim, arg.RoleID, arg.ClaimType, arg.ClaimValue)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM identity_users WHERE id=$1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const deleteUserClaim = `-- name: DeleteUserClaim :exec
DELETE FROM identity_user_claims WHERE user_id=$1 AND claim_type=$2 AND claim_value=$3
`

type DeleteUserClaimParams struct {
	UserID     string
	ClaimType  string
	ClaimValue string
}

func (q *Queries) DeleteUserClaim(ctx context.Context, arg DeleteUserClaimParams) error {
	_, err := q.db.Exec(ctx, deleteUserClaim, arg.UserID, arg.ClaimType, arg.ClaimValue)
	return err
}

const deleteUserToken = `-- name: DeleteUserToken :exec
DELETE FROM identity_user_tokens WHERE user_id=$1 AND login_provider=$2 AND name=$3
`

type DeleteUserTokenParams struct {
	UserID        string
	LoginProvider string
	Name          string
}

func (q *Queries) DeleteUserToken(ctx context.Context, arg DeleteUserTokenParams) error {
	_, err := q.db.Exec(ctx, deleteUserToken, arg.UserID, arg.LoginProvider, arg.Name)
	return err
}

const getActiveAPIKeyByHash = `-- name: GetActiveAPIKeyByHash :one
SELECT id, user_id, name, prefix, key_hash, scopes, expires_at, last_used_at, revoked_at, created_at
FROM identity_api_keys
WHERE key_hash = $1 AND revoked_at IS NULL AND (expires_at IS NULL OR expires_at > now())
`

func (q *Queries) GetActiveAPIKeyByHash(ctx context.Context, keyHash string) (IdentityApiKey, error) {
	row := q.db.QueryRow(ctx, getActiveAPIKeyByHash, keyHash)
	var i IdentityApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.KeyHash,
		&i.Scopes,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, name, normalized_name, concurrency_stamp FROM identity_roles WHERE id=$1
`

func (q *Queries) GetRoleByID(ctx context.Context, id string) (IdentityRole, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i IdentityRole
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NormalizedName,
		&i.ConcurrencyStamp,
	)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, name, normalized_name, concurrency_stamp FROM identity_roles WHERE normalized_name=$1
`

func (q *Queries) GetRoleByName(ctx context.Context, normalizedName string) (IdentityRole, error) {
	row := q.db.QueryRow(ctx, getRoleByName, normalizedName)
	var i IdentityRole
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NormalizedName,
		&i.ConcurrencyStamp,
	)
	return i, err
}

const getRoleClaims = `-- name: GetRoleClaims :many
SELECT claim_type, claim_value FROM identity_role_claims WHERE role_id=$1
`

type GetRoleClaimsRow struct {
	ClaimType  string
	ClaimValue string
}

func (q *Queries) GetRoleClaims(ctx context.Context, roleID string) ([]GetRoleClaimsRow, error) {
	rows, err := q.db.Query(ctx, getRoleClaims, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRoleClaimsRow
	for rows.Next() {
		var i GetRoleClaimsRow
		if err := rows.Scan(&i.ClaimType, &i.ClaimValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoleIDByName = `-- name: GetRoleIDByName :one
SELECT id FROM identity_roles WHERE normalized_name=$1
`

func (q *Queries) GetRoleIDByName(ctx context.Context, normalizedName string) (string, error) {
	row := q.db.QueryRow(ctx, getRoleIDByName, normalizedName)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, user_name, normalized_user_name, email, normalized_email, email_confirmed, password_hash, security_stamp, concurrency_stamp, phone_number, phone_number_confirmed, two_factor_enabled, lockout_end, lockout_enabled, access_failed_count, attributes, is_anonymous, created_at, updated_at FROM identity_users WHERE normalized_email=$1
`

func (q *Queries) GetUserByEmail(ctx context.Context, normalizedEmail string) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, normalizedEmail)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.NormalizedUserName,
		&i.Email,
		&i.NormalizedEmail,
		&i.EmailConfirmed,
		&i.PasswordHash,
		&i.SecurityStamp,
		&i.ConcurrencyStamp,
		&i.PhoneNumber,
		&i.PhoneNumberConfirmed,
		&i.TwoFactorEnabled,
		&i.LockoutEnd,
		&i.LockoutEnabled,
		&i.AccessFailedCount,
		&i.Attributes,
		&i.IsAnonymous,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, user_name, normalized_user_name, email, normalized_email, email_confirmed, password_hash, security_stamp, concurrency_stamp, phone_number, phone_number_confirmed, two_factor_enabled, lockout_end, lockout_enabled, access_failed_count, attributes, is_anonymous, created_at, updated_at FROM identity_users WHERE id=$1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.NormalizedUserName,
		&i.Email,
		&i.NormalizedEmail,
		&i.EmailConfirmed,
		&i.PasswordHash,
		&i.SecurityStamp,
		&i.ConcurrencyStamp,
		&i.PhoneNumber,
		&i.PhoneNumberConfirmed,
		&i.TwoFactorEnabled,
		&i.LockoutEnd,
		&i.LockoutEnabled,
		&i.AccessFailedCount,
		&i.Attributes,
		&i.IsAnonymous,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByName = `-- name: GetUserByName :one
SELECT id, user_name, normalized_user_name, email, normalized_email, email_confirmed, password_hash, security_stamp, concurrency_stamp, phone_number, phone_number_confirmed, two_factor_enabled, lockout_end, lockout_enabled, access_failed_count, attributes, is_anonymous, created_at, updated_at FROM identity_users WHERE normalized_user_name=$1
`

func (q *Queries) GetUserByName(ctx context.Context, normalizedUserName string) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, getUserByName, normalizedUserName)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.NormalizedUserName,
		&i.Email,
		&i.NormalizedEmail,
		&i.EmailConfirmed,
		&i.PasswordHash,
		&i.SecurityStamp,
		&i.ConcurrencyStamp,
		&i.PhoneNumber,
		&i.PhoneNumberConfirmed,
		&i.TwoFactorEnabled,
		&i.LockoutEnd,
		&i.LockoutEnabled,
		&i.AccessFailedCount,
		&i.Attributes,
		&i.IsAnonymous,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserClaims = `-- name: GetUserClaims :many
SELECT claim_type, claim_value FROM identity_user_claims WHERE user_id=$1
`

type GetUserClaimsRow struct {
	ClaimType  string
	ClaimValue string
}

func (q *Queries) GetUserClaims(ctx context.Context, userID string) ([]GetUserClaimsRow, error) {
	rows, err := q.db.Query(ctx, getUserClaims, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserClaimsRow
	for rows.Next() {
		var i GetUserClaimsRow
		if err := rows.Scan(&i.ClaimType, &i.ClaimValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserIDByLogin = `-- name: GetUserIDByLogin :one
SELECT user_id FROM identity_user_logins WHERE login_provider=$1 AND provider_key=$2
`

type GetUserIDByLoginParams struct {
	LoginProvider string
	ProviderKey   string
}

func (q *Queries) GetUserIDByLogin(ctx context.Context, arg GetUserIDByLoginParams) (string, error) {
	row := q.db.QueryRow(ctx, getUserIDByLogin, arg.LoginProvider, arg.ProviderKey)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const getUserLogins = `-- name: GetUserLogins :many
SELECT login_provider, provider_key, provider_display_name
FROM identity_user_logins WHERE user_id=$1
`

type GetUserLoginsRow struct {
	LoginProvider       string
	ProviderKey         string
	ProviderDisplayName string
}

func (q *Queries) GetUserLogins(ctx context.Context, userID string) ([]GetUserLoginsRow, error) {
	rows, err := q.db.Query(ctx, getUserLogins, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserLoginsRow
	for rows.Next() {
		var i GetUserLoginsRow
		if err := rows.Scan(&i.LoginProvider, &i.ProviderKey, &i.ProviderDisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT r.name FROM identity_roles r
JOIN identity_user_roles ur ON ur.role_id = r.id
WHERE ur.user_id=$1
`

func (q *Queries) GetUserRoles(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserToken = `-- name: GetUserToken :one
SELECT value FROM identity_user_tokens
WHERE user_id=$1 AND login_provider=$2 AND name=$3
`

type GetUserTokenParams struct {
	UserID        string
	LoginProvider string
	Name          string
}

func (q *Queries) GetUserToken(ctx context.Context, arg GetUserTokenParams) (string, error) {
	row := q.db.QueryRow(ctx, getUserToken, arg.UserID, arg.LoginProvider, arg.Name)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getUsersForClaim = `-- name: GetUsersForClaim :many
SELECT id, user_name, normalized_user_name, email, normalized_email, email_confirmed, password_hash, security_stamp, concurrency_stamp, phone_number, phone_number_confirmed, two_factor_enabled, lockout_end, lockout_enabled, access_failed_count, attributes, is_anonymous, created_at, updated_at FROM identity_users
WHERE id IN (
    SELECT user_id FROM identity_user_claims WHERE claim_type = $1 AND claim_value = $2
)
ORDER BY id
`

type GetUsersForClaimParams struct {
	ClaimType  string
	ClaimValue string
}

func (q *Queries) GetUsersForClaim(ctx context.Context, arg GetUsersForClaimParams) ([]IdentityUser, error) {
	rows, err := q.db.Query(ctx, getUsersForClaim, arg.ClaimType, arg.ClaimValue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdentityUser
	for rows.Next() {
		var i IdentityUser
		if err := rows.Scan(
			&i.ID,
			&i.UserName,
			&i.NormalizedUserName,
			&i.Email,
			&i.NormalizedEmail,
			&i.EmailConfirmed,
			&i.PasswordHash,
			&i.SecurityStamp,
			&i.ConcurrencyStamp,
			&i.PhoneNumber,
			&i.PhoneNumberConfirmed,
			&i.TwoFactorEnabled,
			&i.LockoutEnd,
			&i.LockoutEnabled,
			&i.AccessFailedCount,
			&i.Attributes,
			&i.IsAnonymous,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersInRole = `-- name: GetUsersInRole :many
SELECT id, user_name, normalized_user_name, email, normalized_email, email_confirmed, password_hash, security_stamp, concurrency_stamp, phone_number, phone_number_confirmed, two_factor_enabled, lockout_end, lockout_enabled, access_failed_count, attributes, is_anonymous, created_at, updated_at FROM identity_users
WHERE id IN (
    SELECT user_id FROM identity_user_roles
    WHERE role_id = (SELECT id FROM identity_roles WHERE normalized_name = $1)
)
ORDER BY id
`

func (q *Queries) GetUsersInRole(ctx context.Context, normalizedName string) ([]IdentityUser, error) {
	rows, err := q.db.Query(ctx, getUsersInRole, normalizedName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdentityUser
	for rows.Next() {
		var i IdentityUser
		if err := rows.Scan(
			&i.ID,
			&i.UserName,
			&i.NormalizedUserName,
			&i.Email,
			&i.NormalizedEmail,
			&i.EmailConfirmed,
			&i.PasswordHash,
			&i.SecurityStamp,
			&i.ConcurrencyStamp,
			&i.PhoneNumber,
			&i.PhoneNumberConfirmed,
			&i.TwoFactorEnabled,
			&i.LockoutEnd,
			&i.LockoutEnabled,
			&i.AccessFailedCount,
			&i.Attributes,
			&i.IsAnonymous,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isUserInRole = `-- name: IsUserInRole :one
SELECT EXISTS(
    SELECT 1 FROM identity_user_roles ur
    JOIN identity_roles r ON r.id = ur.role_id
    WHERE ur.user_id=$1 AND r.normalized_name=$2
)
`

type IsUserInRoleParams struct {
	UserID         string
	NormalizedName string
}

func (q *Queries) IsUserInRole(ctx context.Context, arg IsUserInRoleParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserInRole, arg.UserID, arg.NormalizedName)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listAPIKeysByUser = `-- name: ListAPIKeysByUser :many
SELECT id, user_id, name, prefix, key_hash, scopes, expires_at, last_used_at, revoked_at, created_at
FROM identity_api_keys WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ListAPIKeysByUser(ctx context.Context, userID string) ([]IdentityApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdentityApiKey
	for rows.Next() {
		var i IdentityApiKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Prefix,
			&i.KeyHash,
			&i.Scopes,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, user_name, normalized_user_name, email, normalized_email, email_confirmed, password_hash, security_stamp, concurrency_stamp, phone_number, phone_number_confirmed, two_factor_enabled, lockout_end, lockout_enabled, access_failed_count, attributes, is_anonymous, created_at, updated_at FROM identity_users
WHERE $1::text = '' OR normalized_user_name LIKE '%' || $1 || '%'
   OR normalized_email LIKE '%' || $1 || '%'
ORDER BY id
LIMIT $3 OFFSET $2
`

type ListUsersParams struct {
	Search string
	Off    int32
	Lim    int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]IdentityUser, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Search, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdentityUser
	for rows.Next() {
		var i IdentityUser
		if err := rows.Scan(
			&i.ID,
			&i.UserName,
			&i.NormalizedUserName,
			&i.Email,
			&i.NormalizedEmail,
			&i.EmailConfirmed,
			&i.PasswordHash,
			&i.SecurityStamp,
			&i.ConcurrencyStamp,
			&i.PhoneNumber,
			&i.PhoneNumberConfirmed,
			&i.TwoFactorEnabled,
			&i.LockoutEnd,
			&i.LockoutEnabled,
			&i.AccessFailedCount,
			&i.Attributes,
			&i.IsAnonymous,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeAnonymousUsers = `-- name: PurgeAnonymousUsers :execrows
DELETE FROM identity_users WHERE is_anonymous AND created_at < $1
`

func (q *Queries) PurgeAnonymousUsers(ctx context.Context, createdAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, purgeAnonymousUsers, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removeUserFromRole = `-- name: RemoveUserFromRole :exec
DELETE FROM identity_user_roles WHERE user_id=$1 AND role_id=$2
`

type RemoveUserFromRoleParams struct {
	UserID string
	RoleID string
}

func (q *Queries) RemoveUserFromRole(ctx context.Context, arg RemoveUserFromRoleParams) error {
	_, err := q.db.Exec(ctx, removeUserFromRole, arg.UserID, arg.RoleID)
	return err
}

const removeUserLogin = `-- name: RemoveUserLogin :exec
DELETE FROM identity_user_logins WHERE user_id=$1 AND login_provider=$2 AND provider_key=$3
`

type RemoveUserLoginParams struct {
	UserID        string
	LoginProvider string
	ProviderKey   string
}

func (q *Queries) RemoveUserLogin(ctx context.Context, arg RemoveUserLoginParams) error {
	_, err := q.db.Exec(ctx, removeUserLogin, arg.UserID, arg.LoginProvider, arg.ProviderKey)
	return err
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE identity_api_keys SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAPIKey(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, revokeAPIKey, id)
	return err
}

const roleExists = `-- name: RoleExists :one
SELECT EXISTS(SELECT 1 FROM identity_roles WHERE id=$1)
`

func (q *Queries) RoleExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, roleExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const touchAPIKeyLastUsed = `-- name: TouchAPIKeyLastUsed :exec
UPDATE identity_api_keys SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAPIKeyLastUsed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchAPIKeyLastUsed, id)
	return err
}

const updateRole = `-- name: UpdateRole :execrows
UPDATE identity_roles SET name = $1, normalized_name = $2,
    concurrency_stamp = $3
WHERE id = $4 AND concurrency_stamp = $5
`

type UpdateRoleParams struct {
	Name                string
	NormalizedName      string
	NewConcurrencyStamp string
	ID                  string
	OldConcurrencyStamp string
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRole,
		arg.Name,
		arg.NormalizedName,
		arg.NewConcurrencyStamp,
		arg.ID,
		arg.OldConcurrencyStamp,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUser = `-- name: UpdateUser :execrows
UPDATE identity_users SET
    user_name = $1, normalized_user_name = $2, email = $3,
    normalized_email = $4, email_confirmed = $5,
    password_hash = $6, security_stamp = $7,
    concurrency_stamp = $8, phone_number = $9,
    phone_number_confirmed = $10, two_factor_enabled = $11,
    lockout_end = $12, lockout_enabled = $13,
    access_failed_count = $14, attributes = $15,
    is_anonymous = $16, updated_at = now()
WHERE id = $17 AND concurrency_stamp = $18
`

type UpdateUserParams struct {
	UserName             string
	NormalizedUserName   string
	Email                string
	NormalizedEmail      string
	EmailConfirmed       bool
	PasswordHash         string
	SecurityStamp        string
	NewConcurrencyStamp  string
	PhoneNumber          string
	PhoneNumberConfirmed bool
	TwoFactorEnabled     bool
	LockoutEnd           *time.Time
	LockoutEnabled       bool
	AccessFailedCount    int32
	Attributes           json.RawMessage
	IsAnonymous          bool
	ID                   string
	OldConcurrencyStamp  string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUser,
		arg.UserName,
		arg.NormalizedUserName,
		arg.Email,
		arg.NormalizedEmail,
		arg.EmailConfirmed,
		arg.PasswordHash,
		arg.SecurityStamp,
		arg.NewConcurrencyStamp,
		arg.PhoneNumber,
		arg.PhoneNumberConfirmed,
		arg.TwoFactorEnabled,
		arg.LockoutEnd,
		arg.LockoutEnabled,
		arg.AccessFailedCount,
		arg.Attributes,
		arg.IsAnonymous,
		arg.ID,
		arg.OldConcurrencyStamp,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertUserToken = `-- name: UpsertUserToken :exec
INSERT INTO identity_user_tokens (user_id, login_provider, name, value)
VALUES ($1,$2,$3,$4)
ON CONFLICT (user_id, login_provider, name) DO UPDATE SET value=EXCLUDED.value
`

type UpsertUserTokenParams struct {
	UserID        string
	LoginProvider string
	Name          string
	Value         string
}

func (q *Queries) UpsertUserToken(ctx context.Context, arg UpsertUserTokenParams) error {
	_, err := q.db.Exec(ctx, upsertUserToken,
		arg.UserID,
		arg.LoginProvider,
		arg.Name,
		arg.Value,
	)
	return err
}
