// Package pgxsqlc is a PostgreSQL store whose query layer is generated by sqlc
// (see sqlc.yaml, schema.sql, query.sql; regenerate with `sqlc generate`). It is
// an alternative to the hand-written pgxstore: same schema, fully type-checked
// SQL. This file adapts the generated Queries to the identity store interfaces.
package pgxsqlc

import (
	"context"
	"encoding/json"
	"errors"
	"strings"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/terglos/go-idento/identity"
	gen "github.com/terglos/go-idento/stores/pgxsqlc/internal/sqlcgen"
)

// UserStore implements identity.DefaultUserStore via sqlc-generated queries.
type UserStore struct{ q *gen.Queries }

// RoleStore implements identity.RoleStore via sqlc-generated queries.
type RoleStore struct{ q *gen.Queries }

var (
	_ identity.DefaultUserStore                          = (*UserStore)(nil)
	_ identity.RoleStore                                 = (*RoleStore)(nil)
	_ identity.UserLister[identity.User, *identity.User] = (*UserStore)(nil)
)

func NewUserStore(db *pgxpool.Pool) *UserStore { return &UserStore{q: gen.New(db)} }
func NewRoleStore(db *pgxpool.Pool) *RoleStore { return &RoleStore{q: gen.New(db)} }

func mapNotFound(err error) error {
	if errors.Is(err, pgx.ErrNoRows) {
		return identity.ErrNotFound
	}
	return err
}

func attrsToJSON(a identity.Attributes) json.RawMessage {
	if a == nil {
		return json.RawMessage("{}")
	}
	b, err := json.Marshal(a)
	if err != nil {
		return json.RawMessage("{}")
	}
	return b
}

func toUser(r gen.IdentityUser) *identity.User {
	u := &identity.User{
		ID:                   r.ID,
		UserName:             r.UserName,
		NormalizedUserName:   r.NormalizedUserName,
		Email:                r.Email,
		NormalizedEmail:      r.NormalizedEmail,
		EmailConfirmed:       r.EmailConfirmed,
		PasswordHash:         r.PasswordHash,
		SecurityStamp:        r.SecurityStamp,
		ConcurrencyStamp:     r.ConcurrencyStamp,
		PhoneNumber:          r.PhoneNumber,
		PhoneNumberConfirmed: r.PhoneNumberConfirmed,
		TwoFactorEnabled:     r.TwoFactorEnabled,
		LockoutEnd:           r.LockoutEnd,
		LockoutEnabled:       r.LockoutEnabled,
		AccessFailedCount:    int(r.AccessFailedCount),
		CreatedAt:            r.CreatedAt,
		UpdatedAt:            r.UpdatedAt,
	}
	if len(r.Attributes) > 0 {
		_ = json.Unmarshal(r.Attributes, &u.Attributes)
	}
	return u
}

// --- UserStore ---

func (s *UserStore) Create(ctx context.Context, u *identity.User) error {
	return s.q.CreateUser(ctx, gen.CreateUserParams{
		ID: u.ID, UserName: u.UserName, NormalizedUserName: u.NormalizedUserName,
		Email: u.Email, NormalizedEmail: u.NormalizedEmail, EmailConfirmed: u.EmailConfirmed,
		PasswordHash: u.PasswordHash, SecurityStamp: u.SecurityStamp, ConcurrencyStamp: u.ConcurrencyStamp,
		PhoneNumber: u.PhoneNumber, PhoneNumberConfirmed: u.PhoneNumberConfirmed,
		TwoFactorEnabled: u.TwoFactorEnabled, LockoutEnd: u.LockoutEnd, LockoutEnabled: u.LockoutEnabled,
		AccessFailedCount: int32(u.AccessFailedCount), Attributes: attrsToJSON(u.Attributes),
	})
}

func (s *UserStore) Update(ctx context.Context, u *identity.User) error {
	newStamp := identity.NewConcurrencyStamp()
	n, err := s.q.UpdateUser(ctx, gen.UpdateUserParams{
		ID: u.ID, UserName: u.UserName, NormalizedUserName: u.NormalizedUserName,
		Email: u.Email, NormalizedEmail: u.NormalizedEmail, EmailConfirmed: u.EmailConfirmed,
		PasswordHash: u.PasswordHash, SecurityStamp: u.SecurityStamp,
		NewConcurrencyStamp: newStamp, OldConcurrencyStamp: u.ConcurrencyStamp,
		PhoneNumber: u.PhoneNumber, PhoneNumberConfirmed: u.PhoneNumberConfirmed,
		TwoFactorEnabled: u.TwoFactorEnabled, LockoutEnd: u.LockoutEnd, LockoutEnabled: u.LockoutEnabled,
		AccessFailedCount: int32(u.AccessFailedCount), Attributes: attrsToJSON(u.Attributes),
	})
	if err != nil {
		return err
	}
	if n == 0 {
		if _, e := s.q.GetUserByID(ctx, u.ID); errors.Is(e, pgx.ErrNoRows) {
			return identity.ErrNotFound
		}
		return identity.ErrConcurrencyFailure
	}
	u.ConcurrencyStamp = newStamp
	return nil
}

func (s *UserStore) Delete(ctx context.Context, u *identity.User) error {
	return s.q.DeleteUser(ctx, u.ID)
}

func (s *UserStore) FindByID(ctx context.Context, id string) (*identity.User, error) {
	r, err := s.q.GetUserByID(ctx, id)
	if err != nil {
		return nil, mapNotFound(err)
	}
	return toUser(r), nil
}

func (s *UserStore) FindByName(ctx context.Context, n string) (*identity.User, error) {
	r, err := s.q.GetUserByName(ctx, n)
	if err != nil {
		return nil, mapNotFound(err)
	}
	return toUser(r), nil
}

func (s *UserStore) FindByEmail(ctx context.Context, e string) (*identity.User, error) {
	r, err := s.q.GetUserByEmail(ctx, e)
	if err != nil {
		return nil, mapNotFound(err)
	}
	return toUser(r), nil
}

// ListUsers implements identity.UserLister.
func (s *UserStore) ListUsers(ctx context.Context, f identity.ListFilter) ([]*identity.User, int64, error) {
	search := strings.ToUpper(f.Search)
	total, err := s.q.CountUsers(ctx, search)
	if err != nil {
		return nil, 0, err
	}
	rows, err := s.q.ListUsers(ctx, gen.ListUsersParams{Search: search, Lim: int32(f.Limit), Off: int32(f.Offset)})
	if err != nil {
		return nil, 0, err
	}
	out := make([]*identity.User, len(rows))
	for i, r := range rows {
		out[i] = toUser(r)
	}
	return out, total, nil
}

func (s *UserStore) AddToRole(ctx context.Context, u *identity.User, normalizedRoleName string) error {
	rid, err := s.q.GetRoleIDByName(ctx, normalizedRoleName)
	if err != nil {
		return mapNotFound(err)
	}
	return s.q.AddUserToRole(ctx, gen.AddUserToRoleParams{UserID: u.ID, RoleID: rid})
}

func (s *UserStore) RemoveFromRole(ctx context.Context, u *identity.User, normalizedRoleName string) error {
	rid, err := s.q.GetRoleIDByName(ctx, normalizedRoleName)
	if err != nil {
		return mapNotFound(err)
	}
	return s.q.RemoveUserFromRole(ctx, gen.RemoveUserFromRoleParams{UserID: u.ID, RoleID: rid})
}

func (s *UserStore) GetRoles(ctx context.Context, u *identity.User) ([]string, error) {
	return s.q.GetUserRoles(ctx, u.ID)
}

func (s *UserStore) IsInRole(ctx context.Context, u *identity.User, normalizedRoleName string) (bool, error) {
	return s.q.IsUserInRole(ctx, gen.IsUserInRoleParams{UserID: u.ID, NormalizedName: normalizedRoleName})
}

func (s *UserStore) GetClaims(ctx context.Context, u *identity.User) ([]identity.Claim, error) {
	rows, err := s.q.GetUserClaims(ctx, u.ID)
	if err != nil {
		return nil, err
	}
	out := make([]identity.Claim, len(rows))
	for i, r := range rows {
		out[i] = identity.Claim{Type: r.ClaimType, Value: r.ClaimValue}
	}
	return out, nil
}

func (s *UserStore) AddClaims(ctx context.Context, u *identity.User, claims []identity.Claim) error {
	for _, c := range claims {
		if err := s.q.AddUserClaim(ctx, gen.AddUserClaimParams{UserID: u.ID, ClaimType: c.Type, ClaimValue: c.Value}); err != nil {
			return err
		}
	}
	return nil
}

func (s *UserStore) RemoveClaims(ctx context.Context, u *identity.User, claims []identity.Claim) error {
	for _, c := range claims {
		if err := s.q.DeleteUserClaim(ctx, gen.DeleteUserClaimParams{UserID: u.ID, ClaimType: c.Type, ClaimValue: c.Value}); err != nil {
			return err
		}
	}
	return nil
}

func (s *UserStore) GetToken(ctx context.Context, u *identity.User, loginProvider, name string) (string, error) {
	v, err := s.q.GetUserToken(ctx, gen.GetUserTokenParams{UserID: u.ID, LoginProvider: loginProvider, Name: name})
	if errors.Is(err, pgx.ErrNoRows) {
		return "", nil
	}
	return v, err
}

func (s *UserStore) SetToken(ctx context.Context, u *identity.User, loginProvider, name, value string) error {
	return s.q.UpsertUserToken(ctx, gen.UpsertUserTokenParams{UserID: u.ID, LoginProvider: loginProvider, Name: name, Value: value})
}

func (s *UserStore) RemoveToken(ctx context.Context, u *identity.User, loginProvider, name string) error {
	return s.q.DeleteUserToken(ctx, gen.DeleteUserTokenParams{UserID: u.ID, LoginProvider: loginProvider, Name: name})
}

func (s *UserStore) AddLogin(ctx context.Context, u *identity.User, login identity.UserLoginInfo) error {
	return s.q.AddUserLogin(ctx, gen.AddUserLoginParams{
		LoginProvider: login.LoginProvider, ProviderKey: login.ProviderKey,
		ProviderDisplayName: login.ProviderDisplayName, UserID: u.ID,
	})
}

func (s *UserStore) RemoveLogin(ctx context.Context, u *identity.User, loginProvider, providerKey string) error {
	return s.q.RemoveUserLogin(ctx, gen.RemoveUserLoginParams{UserID: u.ID, LoginProvider: loginProvider, ProviderKey: providerKey})
}

func (s *UserStore) GetLogins(ctx context.Context, u *identity.User) ([]identity.UserLoginInfo, error) {
	rows, err := s.q.GetUserLogins(ctx, u.ID)
	if err != nil {
		return nil, err
	}
	out := make([]identity.UserLoginInfo, len(rows))
	for i, r := range rows {
		out[i] = identity.UserLoginInfo{LoginProvider: r.LoginProvider, ProviderKey: r.ProviderKey, ProviderDisplayName: r.ProviderDisplayName}
	}
	return out, nil
}

func (s *UserStore) FindByLogin(ctx context.Context, loginProvider, providerKey string) (*identity.User, error) {
	uid, err := s.q.GetUserIDByLogin(ctx, gen.GetUserIDByLoginParams{LoginProvider: loginProvider, ProviderKey: providerKey})
	if err != nil {
		return nil, mapNotFound(err)
	}
	return s.FindByID(ctx, uid)
}

// --- RoleStore ---

func (s *RoleStore) Create(ctx context.Context, r *identity.Role) error {
	return s.q.CreateRole(ctx, gen.CreateRoleParams{ID: r.ID, Name: r.Name, NormalizedName: r.NormalizedName, ConcurrencyStamp: r.ConcurrencyStamp})
}

func (s *RoleStore) Update(ctx context.Context, r *identity.Role) error {
	return s.q.UpdateRole(ctx, gen.UpdateRoleParams{ID: r.ID, Name: r.Name, NormalizedName: r.NormalizedName, ConcurrencyStamp: r.ConcurrencyStamp})
}

func (s *RoleStore) Delete(ctx context.Context, r *identity.Role) error {
	return s.q.DeleteRole(ctx, r.ID)
}

func (s *RoleStore) FindByID(ctx context.Context, id string) (*identity.Role, error) {
	r, err := s.q.GetRoleByID(ctx, id)
	if err != nil {
		return nil, mapNotFound(err)
	}
	return &identity.Role{ID: r.ID, Name: r.Name, NormalizedName: r.NormalizedName, ConcurrencyStamp: r.ConcurrencyStamp}, nil
}

func (s *RoleStore) FindByName(ctx context.Context, normalizedName string) (*identity.Role, error) {
	r, err := s.q.GetRoleByName(ctx, normalizedName)
	if err != nil {
		return nil, mapNotFound(err)
	}
	return &identity.Role{ID: r.ID, Name: r.Name, NormalizedName: r.NormalizedName, ConcurrencyStamp: r.ConcurrencyStamp}, nil
}

func (s *RoleStore) GetClaims(ctx context.Context, r *identity.Role) ([]identity.Claim, error) {
	rows, err := s.q.GetRoleClaims(ctx, r.ID)
	if err != nil {
		return nil, err
	}
	out := make([]identity.Claim, len(rows))
	for i, row := range rows {
		out[i] = identity.Claim{Type: row.ClaimType, Value: row.ClaimValue}
	}
	return out, nil
}

func (s *RoleStore) AddClaim(ctx context.Context, r *identity.Role, c identity.Claim) error {
	return s.q.AddRoleClaim(ctx, gen.AddRoleClaimParams{RoleID: r.ID, ClaimType: c.Type, ClaimValue: c.Value})
}

func (s *RoleStore) RemoveClaim(ctx context.Context, r *identity.Role, c identity.Claim) error {
	return s.q.DeleteRoleClaim(ctx, gen.DeleteRoleClaimParams{RoleID: r.ID, ClaimType: c.Type, ClaimValue: c.Value})
}
